version: "3.9"  # optional since v1.27.0
services:
  
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME:admin
      - MONGO_INITDB_ROOT_PASSWORD:password
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8093:8081"

  backend:
    build: ./Express
    ports:
      - "8091:4000"
    restart: unless-stopped
    depends_on:
      - mongo
    
  frontend:
     build: ./app
     ports:
      - "5000:3000"




